version: '3.8'
services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - './mysql-data:/var/lib/mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
